name: RideLink CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-account-service:
    name: Build and Test Account Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build and test account-service
        working-directory: ./account-service
        run: mvn clean install

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: account-service-test-results
          path: account-service/target/surefire-reports/

  build-fare-payment-service:
    name: Build and Test Fare Payment Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build and test fare-payment-service
        working-directory: ./fare-payment-service
        run: mvn clean install

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fare-payment-service-test-results
          path: fare-payment-service/target/surefire-reports/
